// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ProductID   int    `json:"productId"`
	CompanyCd   int    `json:"companyCd"`
	InventoryCd int    `json:"inventoryCd"`
	PriceJpy    int    `json:"priceJpy"`
	ProductName string `json:"productName"`
	Description string `json:"description"`
}

type Station struct {
	StationCd       int        `json:"stationCD"`
	LineName        *string    `json:"lineName"`
	StationName     string     `json:"stationName"`
	Address         *string    `json:"address"`
	BeforeStation   *Station   `json:"beforeStation"`
	AfterStation    *Station   `json:"afterStation"`
	TransferStation []*Station `json:"transferStation"`
}
