// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// ProductByCompanyCd represents a row from '[custom product_by_company_cd]'.
type ProductByCompanyCd struct {
	ProductID   int    // product_id
	CompanyCd   int    // company_cd
	InventoryCd int    // inventory_cd
	PriceJpy    int    // price_jpy
	ProductName string // product_name
	Description string // description
}

// ProductByCompanyCdsByCompanyCd runs a custom query, returning results as ProductByCompanyCd.
func ProductByCompanyCdsByCompanyCd(db XODB, companyCd int) ([]*ProductByCompanyCd, error) {
	var err error

	// sql query
	const sqlstr = `select p.product_id,p.company_cd,p.inventory_cd,p.price_jpy,p.product_name,p.description ` +
		`from product p ` +
		`where p.company_cd = $1`

	// run query
	XOLog(sqlstr, companyCd)
	q, err := db.Query(sqlstr, companyCd)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*ProductByCompanyCd{}
	for q.Next() {
		pbcc := ProductByCompanyCd{}

		// scan
		err = q.Scan(&pbcc.ProductID, &pbcc.CompanyCd, &pbcc.InventoryCd, &pbcc.PriceJpy, &pbcc.ProductName, &pbcc.Description)
		if err != nil {
			return nil, err
		}

		res = append(res, &pbcc)
	}

	return res, nil
}
