// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// ProductById represents a row from '[custom product_by_id]'.
type ProductById struct {
	ProductID   int    // product_id
	CompanyCd   int    // company_cd
	InventoryCd int    // inventory_cd
	PriceJpy    int    // price_jpy
	ProductName string // product_name
	Description string // description
}

// ProductByIdsByProductId runs a custom query, returning results as ProductById.
func ProductByIdsByProductId(db XODB, productId int) ([]*ProductById, error) {
	var err error

	// sql query
	const sqlstr = `select p.product_id,p.company_cd,p.inventory_cd,p.price_jpy,p.product_name,p.description ` +
		`from product p ` +
		`where p.product_id = $1`

	// run query
	XOLog(sqlstr, productId)
	q, err := db.Query(sqlstr, productId)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*ProductById{}
	for q.Next() {
		pb := ProductById{}

		// scan
		err = q.Scan(&pb.ProductID, &pb.CompanyCd, &pb.InventoryCd, &pb.PriceJpy, &pb.ProductName, &pb.Description)
		if err != nil {
			return nil, err
		}

		res = append(res, &pb)
	}

	return res, nil
}
